using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace TestsClassGenerator
{
    public class TestClassGenerator
    {
        public List<string> GenerateTestClasses(string sourceCode)
        {
            var result = new List<string>();
            
            SyntaxTree syntaxTree = CSharpSyntaxTree.ParseText(sourceCode);
            List<ClassDeclarationSyntax> classes = syntaxTree.GetRoot().DescendantNodes().OfType<ClassDeclarationSyntax>().ToList();

            int index = 0;
            foreach (var classDeclaration in classes)
            {
                List<MethodDeclarationSyntax> methods = classDeclaration.DescendantNodes()
                    .OfType<MethodDeclarationSyntax>().ToList().Where(method => method.Modifiers.ToList().Any(token => token.Text != "pivate")).ToList();
                
                result[index] += "using Xunit;\n";
                result[index] += "\n";
                result[index] += "namespace TestProject\n";
                result[index] += "{\n";
                result[index] += "\tpublic class Tests";
                result[index] += "\t{\n";
                
                foreach(var method in methods)
                { 
                    Console.WriteLine(((ClassDeclarationSyntax)method.Parent)?.Identifier.ValueText + method.Identifier);
                    result[index] += "\t\t[Fact]\n";
                    result[index] += "\t\tpublic void " + ((ClassDeclarationSyntax)method.Parent)?.Identifier.ValueText + method.Identifier + "()" + "\n";
                    result[index] += "\t\t{\n";
                    result[index] += "\t\t\tAssert.True(false, \"autogenerated\");\n";
                    result[index] += "\t\t}\n";
                    result[index] += "\t\t\n";
                }

                result[index] += "\t}\n}\n";
                index += 1;
            }
            
            return result;
        }
    }
}